"""IBSI code-to-name mapping."""

CODE_TO_NAME = {
    "0F91": "Global intensity peak",
    "0GBI": "Small distance emphasis",
    "1128": "Intensity Robust mean absolute deviation",
    "12CE": "Maximum histogram gradient",
    "1GSF": "Minimum intensity",
    "1PFV": "Grey level variance",
    "1PR": "10th discretised intensity percentile",
    "1PR8": "Minimum discretised intensity",
    "1QCO": "Normalised inverse difference moment",
    "1X9X": "Strength",
    "22OV": "Short runs emphasis",
    "25C7": "Asphericity",
    "2OJQ": "Intensity range",
    "2PR5": "Surface to volume ratio",
    "3KUM": "Long run high grey level emphasis",
    "3NCY": "Maximum discretised intensity",
    "3NSA": "Zone size variance",
    "48P8": "Large zone emphasis",
    "4FUA": "Intensity Mean absolute deviation",
    "4JP3": "Zone size non-uniformity",
    "4RNL": "Intensity histogram median absolute deviation",
    "5GN9": "High grey level zone emphasis",
    "5RAI": "Small zone low grey level emphasis",
    "5SPA": "Normalised grey level non-uniformity",
    "5Z3W": "Discretised intensity range",
    "5ZWQ": "Root mean square intensity",
    "60VM": "Joint average",
    "65HE": "Contrast",
    "6BDE": "Volume density (AEE)",
    "6XV8": "Dependence count percentage",
    "7HP3": "Normalised grey level non-uniformity",
    "7J51": "Least axis length",
    "7NFM": "Cluster shade",
    "7T7F": "Area density (convex hull)",
    "7TET": "Intensity Coefficient of variation",
    "7WT1": "Zone distance variance",
    "84IY": "Maximum intensity",
    "88K1": "Discretised intensity skewness",
    "8CE5": "Grey level variance",
    "8DWT": "90th intensity percentile",
    "8E6O": "Maximum histogram gradient intensity",
    "8S9J": "Dissimilarity",
    "8ZQL": "Angular second moment",
    "99N0": "Integrated intensity",
    "9CMM": "Area under the IVH curve",
    "9QMG": "High dependence high grey level emphasis",
    "9S40": "Intensity Quartile coefficient of dispersion",
    "9ZK5": "Run percentage",
    "A7WM": "Large distance low grey level emphasis",
    "ACUI": "Contrast",
    "AE86": "Cluster prominence",
    "AMMC": "Intensity histogram mode",
    "BC2M_10": "Volume at intensity fraction 0.10",
    "BC2M_90": "Volume at intensity fraction 0.90",
    "BJ5W": "Discretised intensity uniformity",
    "BQWJ": "Compactness 2",
    "BRI8": "Area density (MVEE)",
    "BYLV": "Grey level variance",
    "C0JK": "Surface area",
    "C3I7": "Discretised intensity kurtosis",
    "CAS9": "Dependence count energy",
    "CH89": "Discretised intensity variance",
    "CNV2": "Intensity fraction difference between volume 0.10 and 0.90 fractions",
    "CWYJ": "Intensity histogram coefficient of variation",
    "D2ZX": "Intensity histogram mean absolute deviation",
    "D3YU": "Difference variance",
    "DDTU": "Volume fraction difference between intensity 0.10 and 0.90 fractions",
    "DG8W": "Cluster tendency",
    "DKNJ": "Small distance high grey level emphasis",
    "DNX2": "Dependence count variance",
    "E8JP": "Inverse variance",
    "ECT3": "Intensity variance",
    "EQ3F": "Low dependence low grey level emphasis",
    "FCBV": "Dependence count entropy",
    "FP8K": "Grey level non-uniformity",
    "G3QZ": "High grey level run emphasis",
    "GBDU": "Zone distance entropy",
    "GBPN_10": "Intensity at volume fraction 0.10",
    "GBPN_90": "Intensity at volume fraction 0.90",
    "GD3A": "Short run high grey level emphasis",
    "GPMT": "90th discretised intensity percentile",
    "GU8N": "Zone size entropy",
    "GYBY": "Joint maximum",
    "HDEZ": "Complexity",
    "HJ9O": "Run entropy",
    "HTZT": "Short run low grey level emphasis",
    "HW1V": "Small zone high grey level emphasis",
    "IATH": "Normalised zone distance non-uniformity",
    "IB1Z": "Inverse difference",
    "IC23": "Normalised run length non-uniformity",
    "IMOQ": "High dependence emphasis",
    "IPH6": "Intensity kurtosis",
    "IQYR": "Area density (OMBB)",
    "IVPO": "Long run low grey level emphasis",
    "J17V": "Large zone high grey level emphasis",
    "JA6D": "Low dependence high grey level emphasis",
    "JN9H": "Information correlation 2",
    "JNSA": "Grey level non-uniformity",
    "K26C": "High grey level zone emphasis",
    "KE2A": "Intensity skewness",
    "KLMA": "Center of mass shift",
    "KLTH": "Large distance high grey level emphasis",
    "KRCK": "Spherical disproportion",
    "L0JK": "Maximum 3D diameter",
    "MB4I": "Large distance emphasis",
    "N17B": "Flatness",
    "N365": "Moran's I index",
    "N72L": "Intensity Median absolute deviation",
    "N8CA": "Intensity energy",
    "NBZI": "High dependence low grey level emphasis",
    "NDRX": "Normalised inverse difference",
    "NI2N": "Correlation",
    "NPT7": "Geary's C measure",
    "NQ30": "Busyness",
    "NTRS": "Difference entropy",
    "OAE7": "High grey level count emphasis",
    "OEEB": "Sum variance",
    "OKJI": "Normalised dependence count non-uniformity",
    "OVBL": "Normalised grey level non-uniformity",
    "P001": "Small zone emphasis",
    "P30P": "Zone percentage",
    "P6QZ": "Sum entropy",
    "P9VJ": "Minor axis length",
    "PBX1": "Volume density (AABB)",
    "Q3CK": "Elongation",
    "Q4LE": "Mean intensity",
    "QCDE": "Coarseness",
    "QCFX": "Sphericity",
    "QG58": "10th intensity percentile",
    "QK93": "Grey level variance",
    "QWB0": "Autocorrelation",
    "R3ER": "Volume density (convex hull)",
    "R59B": "Area density (AABB)",
    "R5YN": "Grey level non-uniformity",
    "R8DG": "Information correlation 1",
    "RDD2": "Area density (AEE)",
    "RHQZ": "Minimum histogram gradient intensity",
    "RNU0": "Volume",
    "RUVG": "Small distance low grey level emphasis",
    "S1RA": "Low grey level zone emphasis",
    "SALO": "Intensity interquartile range",
    "SKGS": "Compactness 1",
    "SLWD": "Intensity histogram quartile coefficient of dispersion",
    "SODN": "Low dependence emphasis",
    "SWZ1": "Volume density (MVEE)",
    "SXLW": "Run length variance",
    "TDIC": "Major axis length",
    "TF7R": "Difference average",
    "TL9H": "Low grey level count emphasis",
    "TLU2": "Discretised intensity entropy",
    "TU9B": "Joint entropy",
    "UR99": "Joint variance",
    "V294": "Zone distance non-uniformity",
    "V3SW": "Low grey level run emphasis",
    "VB3A": "Normalised zone size non-uniformity",
    "VFT7": "Grey level non-uniformity",
    "VIWW": "Zone percentage",
    "VJGA": "Local intensity peak ",
    "VQB3": "Minimum histogram gradient",
    "W4KF": "Long runs emphasis",
    "W92Y": "Run length non-uniformity",
    "WF0Z": "Inverse difference moment",
    "WIFQ": "Median discretised intensity",
    "WR0O": "Discretised intensity interquartile range",
    "WRZB": "Intensity histogram robust mean absolute deviation",
    "X6K6": "Mean discretised intensity",
    "XMSY": "Low grey level zone emphasis",
    "Y12H": "Median intensity",
    "Y1RO": "Normalised grey level non-uniformity",
    "YEKZ": "Volume voxel counting",
    "YH51": "Large zone low grey level emphasis",
    "Z87G": "Dependence count non-uniformity",
    "ZGXS": "Sum average",
    "ZH1A": "Volume density (OMBB)",
}
