"""IBSI code-to-family mapping."""

CODE_TO_FAMILY = {
    "0F91": "local_intensity",
    "0GBI": "gldzm",
    "1128": "intensity",
    "12CE": "histogram",
    "1GSF": "intensity",
    "1PFV": "ngldm",
    "1PR": "histogram",
    "1PR8": "histogram",
    "1QCO": "glcm",
    "1X9X": "ngtdm",
    "22OV": "glrlm",
    "25C7": "morphology",
    "2OJQ": "intensity",
    "2PR5": "morphology",
    "3KUM": "glrlm",
    "3NCY": "histogram",
    "3NSA": "glszm",
    "48P8": "glszm",
    "4FUA": "intensity",
    "4JP3": "glszm",
    "4RNL": "histogram",
    "5GN9": "glszm",
    "5RAI": "glszm",
    "5SPA": "ngldm",
    "5Z3W": "histogram",
    "5ZWQ": "intensity",
    "60VM": "glcm",
    "65HE": "ngtdm",
    "6BDE": "morphology",
    "6XV8": "ngldm",
    "7HP3": "gldzm",
    "7J51": "morphology",
    "7NFM": "glcm",
    "7T7F": "morphology",
    "7TET": "intensity",
    "7WT1": "gldzm",
    "84IY": "intensity",
    "88K1": "histogram",
    "8CE5": "glrlm",
    "8DWT": "intensity",
    "8E6O": "histogram",
    "8S9J": "glcm",
    "8ZQL": "glcm",
    "99N0": "morphology",
    "9CMM": "ivh",
    "9QMG": "ngldm",
    "9S40": "intensity",
    "9ZK5": "glrlm",
    "A7WM": "gldzm",
    "ACUI": "glcm",
    "AE86": "glcm",
    "AMMC": "histogram",
    "BC2M_10": "ivh",
    "BC2M_90": "ivh",
    "BJ5W": "histogram",
    "BQWJ": "morphology",
    "BRI8": "morphology",
    "BYLV": "glszm",
    "C0JK": "morphology",
    "C3I7": "histogram",
    "CAS9": "ngldm",
    "CH89": "histogram",
    "CNV2": "ivh",
    "CWYJ": "histogram",
    "D2ZX": "histogram",
    "D3YU": "glcm",
    "DDTU": "ivh",
    "DG8W": "glcm",
    "DKNJ": "gldzm",
    "DNX2": "ngldm",
    "E8JP": "glcm",
    "ECT3": "intensity",
    "EQ3F": "ngldm",
    "FCBV": "ngldm",
    "FP8K": "ngldm",
    "G3QZ": "glrlm",
    "GBDU": "gldzm",
    "GBPN_10": "ivh",
    "GBPN_90": "ivh",
    "GD3A": "glrlm",
    "GPMT": "histogram",
    "GU8N": "glszm",
    "GYBY": "glcm",
    "HDEZ": "ngtdm",
    "HJ9O": "glrlm",
    "HTZT": "glrlm",
    "HW1V": "glszm",
    "IATH": "gldzm",
    "IB1Z": "glcm",
    "IC23": "glrlm",
    "IMOQ": "ngldm",
    "IPH6": "intensity",
    "IQYR": "morphology",
    "IVPO": "glrlm",
    "J17V": "glszm",
    "JA6D": "ngldm",
    "JN9H": "glcm",
    "JNSA": "glszm",
    "K26C": "gldzm",
    "KE2A": "intensity",
    "KLMA": "morphology",
    "KLTH": "gldzm",
    "KRCK": "morphology",
    "L0JK": "morphology",
    "MB4I": "gldzm",
    "N17B": "morphology",
    "N365": "morphology",
    "N72L": "intensity",
    "N8CA": "intensity",
    "NBZI": "ngldm",
    "NDRX": "glcm",
    "NI2N": "glcm",
    "NPT7": "morphology",
    "NQ30": "ngtdm",
    "NTRS": "glcm",
    "OAE7": "ngldm",
    "OEEB": "glcm",
    "OKJI": "ngldm",
    "OVBL": "glrlm",
    "P001": "glszm",
    "P30P": "glszm",
    "P6QZ": "glcm",
    "P9VJ": "morphology",
    "PBX1": "morphology",
    "Q3CK": "morphology",
    "Q4LE": "intensity",
    "QCDE": "ngtdm",
    "QCFX": "morphology",
    "QG58": "intensity",
    "QK93": "gldzm",
    "QWB0": "glcm",
    "R3ER": "morphology",
    "R59B": "morphology",
    "R5YN": "glrlm",
    "R8DG": "glcm",
    "RDD2": "morphology",
    "RHQZ": "histogram",
    "RNU0": "morphology",
    "RUVG": "gldzm",
    "S1RA": "gldzm",
    "SALO": "intensity",
    "SKGS": "morphology",
    "SLWD": "histogram",
    "SODN": "ngldm",
    "SWZ1": "morphology",
    "SXLW": "glrlm",
    "TDIC": "morphology",
    "TF7R": "glcm",
    "TL9H": "ngldm",
    "TLU2": "histogram",
    "TU9B": "glcm",
    "UR99": "glcm",
    "V294": "gldzm",
    "V3SW": "glrlm",
    "VB3A": "glszm",
    "VFT7": "gldzm",
    "VIWW": "gldzm",
    "VJGA": "local_intensity",
    "VQB3": "histogram",
    "W4KF": "glrlm",
    "W92Y": "glrlm",
    "WF0Z": "glcm",
    "WIFQ": "histogram",
    "WR0O": "histogram",
    "WRZB": "histogram",
    "X6K6": "histogram",
    "XMSY": "glszm",
    "Y12H": "intensity",
    "Y1RO": "glszm",
    "YEKZ": "morphology",
    "YH51": "glszm",
    "Z87G": "ngldm",
    "ZGXS": "glcm",
    "ZH1A": "morphology",
}
FAMILY_LABELS = {
    "glcm": "GLCM",
    "gldzm": "GLDZM",
    "glrlm": "GLRLM",
    "glszm": "GLSZM",
    "histogram": "Intensity histogram",
    "intensity": "Intensity",
    "ivh": "IVH",
    "local_intensity": "Local intensity",
    "morphology": "Morphology",
    "ngldm": "NGLDM",
    "ngtdm": "NGTDM",
}
FAMILY_ORDER = [
    "morphology",
    "local_intensity",
    "intensity",
    "histogram",
    "ivh",
    "glcm",
    "glrlm",
    "glszm",
    "gldzm",
    "ngtdm",
    "ngldm",
]
